### ISSUE TITLE
off notes

### ISSUE THREAD

**Issue by hydralica** [Anton-To/GmodPiano#3]
some midi files that I tried sounded out of tune on some notes even though in a DAW the midi sounds just fine

**Comment by Anton-To** [comment]
Could you provide the midi files that soud off please

**Comment by hydralica** [comment]
http://www.piano-midi.de/midis/beethoven/mond_3.mid

**Comment by hydralica** [comment]
I just tested it out on a singleplayer session and I didn't have the same off-note problem I did before on a server. I believe there is an issue with the delay and its going so fast that the server cant handle it.

**Comment by Anton-To** [comment]
The best action is to decrease bpm of fast paced songs with any midi editor since the game server can't handle so many keys being pressed at once
